# Generated by Django 2.1.7 on 2019-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20190309_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
