# Generated by Django 2.1.7 on 2019-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_beer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(null=True, upload_to='media/uploads/'),
        ),
    ]
